language: rust
os:
  - linux
  - osx
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email: false
before_script:
  - export PATH=$PATH:~/.cargo/bin
  # If this is a linux environment then point /user/bin/c++ to clang
  # This is extremely hacky.
  - if [ "$(readlink $(which c++))" == "/etc/alternatives/c++" ]; then sudo rm /usr/bin/c++; sudo ln -s /usr/local/clang-5.0.0/bin/clang++ /usr/bin/c++; fi
  - c++ --version
script:
  - cargo build --verbose
  - cargo test --verbose
