on: [push, pull_request]

name: Cargo Format

jobs:
  fmt:
    name: Cargo Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo +nightly fmt --all -- --check
