on: [push, pull_request]

name: Cargo Test

jobs:
  test:
    name: Cargo Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Run Tests
        run: cargo test
